### ISSUE TITLE
More suitable color for code rulers

### ISSUE THREAD

**Issue by krutoo** [siddharthkp/codesandbox-black-vscode-theme#1]
Hi, this theme is really cool for me. But code editor rulers looks too aggressive in macboock pro and vscode 1.45.1

This is an example:
![image](https://user-images.githubusercontent.com/13140130/83868399-3d859200-a744-11ea-9b98-ce4947b35804.png)

Just want to suggest more suitable color for rulers...

**Comment by siddharthkp** [comment]
Yikes, that looks pretty bad

I'd be happy to accept a PR that changes it. I think `tokens.grays[600]` would be perfect as it matches the borders

This is the file to modify: https://github.com/siddharthkp/codesandbox-black-vscode-theme/blob/master/theme.js
